import marimo

__generated_with = "0.23.16"
app = marimo.App()


@app.cell
def _():
    import marimo as mo

    return (mo,)


@app.cell
def _():
    """An example to introduce running PROCESS"""
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    # Introduction to running PROCESS
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    A Jupyter notebook to demonstrate usage of the `process` package.
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    <div class="alert alert-block alert-info">
    <b>NOTE</b> We run the examples in a temporary directory so all the inputs are copied
    there and the outputs contained there before the directory is removed when the example
    has finished running.
    This keeps the examples directory tidy and does not permanently modify any data files.
    The use of temporary directories is not needed for regular use of PROCESS.
    </div>
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    Process can be run from the command line with the `process` command or as a standard
    python package.
    Using process as a package allows for more complex scripting of a process run for
    different tasks.
    """)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Basic run of Process
    Run Process on an input file using the `SingleRun` class.
    This outputs an `MFILE.DAT` and an `OUT.DAT`.

    This is equivalent to running `process -i data/large_tokamak_IN.DAT`
    in the examples folder.
    """)
    return


@app.cell
def _():
    hide_code = True
    import subprocess

    subprocess.call(["pip", "install", "-q", "git+https://github.com/ukaea/PROCESS"])

    from fsspec.implementations.github import GithubFileSystem

    process_repo = GithubFileSystem(org="ukaea", repo="PROCESS", branch="main")

    INDAT_path = "github://examples/data/large_tokamak_IN.DAT"
    INDAT = process_repo.download(
        INDAT_path,
        "",
    )
    return


@app.cell
def _():
    # magic command not supported in marimo; please file an issue to add support
    # %load_ext autoreload
    # '%autoreload 2' command supported automatically in marimo

    from pathlib import Path

    from process.main import SingleRun


    input_path = Path("large_tokamak_IN.DAT")

    single_run = SingleRun(input_path.as_posix())
    single_run.run()
    return (single_run,)


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## Plot summary
    Create a summary of the generated `MFILE.DAT` using `plot_summary`.

    You can also call `plot_summary` from the cli with `process plot summary`
    """)
    return


@app.cell
def _(single_run):
    from process.core.io.plot import plot_summary

    # Pdf and png output are also available
    plot_summary(single_run.mfile_path, output_format="none", show=True)
    return


@app.cell(hide_code=True)
def _(mo):
    mo.md(r"""
    ## View key output variables
    Using the `MFILE` we generated by running the large tokamak scenario above,
    we have set some values on the `CostModel` instance and can print them.
    """)
    return


@app.cell
def _(single_run):
    # Print some values on the CostModel instance
    print(f"Heat transport system: {single_run.data.costs.c226:.3e} M$")
    print(f"Electrical plant equipment: {single_run.data.costs.c24:.3e} M$")
    return


if __name__ == "__main__":
    app.run()
